# Shadow Optimizer V2 - módulos 01 a 25
# Todos os módulos começam em modo análise e não removem dados automaticamente.
$Shadow25Root = Split-Path -Parent $MyInvocation.MyCommand.Path
function Out-ShadowReport { param([string]$Name,[object]$Data) $dir=Join-Path $Shadow25Root 'logs'; New-Item -ItemType Directory -Force $dir | Out-Null; $file=Join-Path $dir ("module-{0}-{1}.json" -f $Name,(Get-Date -Format yyyyMMdd-HHmmss)); $Data | ConvertTo-Json -Depth 8 | Set-Content $file -Encoding UTF8; Write-Host "Relatório salvo: $file" -ForegroundColor Green }
function Get-ShadowHealth { $os=Get-CimInstance Win32_OperatingSystem; $disks=Get-CimInstance Win32_LogicalDisk -Filter 'DriveType=3'; [pscustomobject]@{RAMLivreGB=[math]::Round($os.FreePhysicalMemory/1MB,2);Discos=$disks|Select DeviceID,@{n='LivreGB';e={[math]::Round($_.FreeSpace/1GB,1)}},@{n='TamanhoGB';e={[math]::Round($_.Size/1GB,1)}};UltimoBoot=$os.LastBootUpTime} }
function Get-ShadowBottleneck { Get-Counter '\Processor(_Total)\% Processor Time','\Memory\% Committed Bytes In Use','\LogicalDisk(_Total)\% Disk Time' -SampleInterval 1 -MaxSamples 1 | Select -Expand CounterSamples | Select Path,@{n='Valor';e={[math]::Round($_.CookedValue,1)}} }
function Get-ShadowDiskHealth { Get-CimInstance Win32_DiskDrive | Select Model,SerialNumber,Status,InterfaceType,Size }
function Find-ShadowLargeFiles { param([string]$Path=$env:USERPROFILE,[int]$Top=30) Get-ChildItem $Path -File -Recurse -Force -ErrorAction SilentlyContinue | Sort Length -Descending | Select -First $Top FullName,@{n='MB';e={[math]::Round($_.Length/1MB,1)}} }
function Find-ShadowDuplicates { param([string]$Path=$env:USERPROFILE) Get-ChildItem $Path -File -Recurse -Force -ErrorAction SilentlyContinue | Group-Object Length | Where Count -gt 1 | ForEach-Object { $_.Group | Get-FileHash -Algorithm SHA256 -ErrorAction SilentlyContinue } | Group-Object Hash | Where Count -gt 1 | Select Name,Count }
function Get-ShadowDrivers { Get-CimInstance Win32_PnPSignedDriver | Select DeviceName,DriverVersion,Manufacturer,IsSigned,ProblemCode | Sort ProblemCode }
function Get-ShadowSecurity { [pscustomobject]@{Defender=(Get-MpComputerStatus -ErrorAction SilentlyContinue | Select AMServiceEnabled,AntivirusEnabled,RealTimeProtectionEnabled);Firewall=(Get-NetFirewallProfile -ErrorAction SilentlyContinue | Select Name,Enabled);SecureBoot=(try{Confirm-SecureBootUEFI -ErrorAction Stop}catch{'Não disponível'});TPM=(Get-Tpm -ErrorAction SilentlyContinue | Select TpmPresent,TpmReady)} }
function Get-ShadowPrivacy { Get-Process | Select -First 30 ProcessName,Id,Path | Sort ProcessName }
function Get-ShadowTasks { Get-ScheduledTask -ErrorAction SilentlyContinue | Select TaskName,TaskPath,State,Author | Sort TaskPath,TaskName }
function Get-ShadowBrowsers { Get-Process chrome,msedge,firefox,brave -ErrorAction SilentlyContinue | Select ProcessName,Id,CPU,WorkingSet64 }
function Register-ShadowMaintenance { param([string]$TaskName='Shadow Optimizer - análise semanal') Write-Host 'Criação de tarefa agendada requer confirmação e execução elevada.' -ForegroundColor Yellow; Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue }
function Test-ShadowUpdate { [pscustomobject]@{CurrentVersion='2.0';UpdateSource='Configure em store.json';Status='Somente consulta'} }
function Get-ShadowPlugins { Get-ChildItem (Join-Path $Shadow25Root 'plugins') -File -ErrorAction SilentlyContinue | Select Name,Length,LastWriteTime }
function Get-ShadowGameLibraries { Get-ChildItem ${env:ProgramFiles(x86)} -Directory -ErrorAction SilentlyContinue | Where Name -match 'Steam|Epic|Xbox' | Select FullName }
function Get-ShadowShaderCaches { $paths=@("$env:LOCALAPPDATA\D3DSCache","$env:LOCALAPPDATA\NVIDIA\DXCache","$env:LOCALAPPDATA\AMD\DxCache"); foreach($p in $paths){if(Test-Path $p){$s=(Get-ChildItem $p -Recurse -File -ErrorAction SilentlyContinue|Measure Length -Sum).Sum;[pscustomobject]@{Path=$p;SizeMB=[math]::Round($s/1MB,1)}}} }
function Get-ShadowLaptop { Get-CimInstance Win32_Battery -ErrorAction SilentlyContinue | Select Name,BatteryStatus,EstimatedChargeRemaining,EstimatedRunTime }
function Get-ShadowTemperatures { Get-Counter '\Thermal Zone Information(*)\Temperature' -ErrorAction SilentlyContinue | Select -Expand CounterSamples | Select Path,CookedValue }
function Test-ShadowStability { Write-Host 'Modo seguro: coleta de contadores por 30 segundos, sem estresse artificial.' -ForegroundColor Yellow; 1..30|%{Get-Counter '\Processor(_Total)\% Processor Time' -SampleInterval 1 -MaxSamples 1|Select -Expand CounterSamples|Select @{n='Segundo';e={$_}},CookedValue} }
function Get-ShadowCrashReport { Get-WinEvent -FilterHashtable @{LogName='System';Level=1,2} -MaxEvents 50 -ErrorAction SilentlyContinue | Select TimeCreated,ProviderName,Id,LevelDisplayName,Message }
function Repair-ShadowCommon { param([ValidateSet('Network','Explorer','SystemFiles')][string]$Target='Network') Write-Host "Assistente ${Target}: análise iniciada. Nenhuma alteração automática foi feita." -ForegroundColor Yellow }
function Get-ShadowProcessRules { Get-Process | Sort CPU -Descending -ErrorAction SilentlyContinue | Select -First 20 ProcessName,Id,PriorityClass,CPU }
function Get-ShadowRecommendations { $h=Get-ShadowHealth; if($h.RAMLivreGB -lt 2){'Investigar processos que usam muita RAM.'}; 'Executar primeiro o diagnóstico e o benchmark antes de aplicar mudanças.' }
function Compare-ShadowProfiles { Get-ChildItem (Join-Path $Shadow25Root 'logs') -Filter 'benchmark-*.csv' -ErrorAction SilentlyContinue | Select Name,LastWriteTime,Length }
function Restore-ShadowAll { Get-ChildItem (Join-Path $Shadow25Root 'backups') -Filter '*.json' -ErrorAction SilentlyContinue | Sort LastWriteTime -Descending | Select -First 20 Name,LastWriteTime }
function Show-ShadowBranding { Get-Content (Join-Path $Shadow25Root 'store.json') -Raw | ConvertFrom-Json | Select brand,tagline,storeUrl,supportUrl }
$Shadow25Modules = [ordered]@{1='Get-ShadowHealth';2='Get-ShadowBottleneck';3='Get-ShadowDiskHealth';4='Find-ShadowLargeFiles';5='Find-ShadowDuplicates';6='Get-ShadowDrivers';7='Get-ShadowSecurity';8='Get-ShadowPrivacy';9='Get-ShadowTasks';10='Get-ShadowBrowsers';11='Register-ShadowMaintenance';12='Test-ShadowUpdate';13='Get-ShadowPlugins';14='Get-ShadowGameLibraries';15='Get-ShadowShaderCaches';16='Get-ShadowLaptop';17='Get-ShadowTemperatures';18='Test-ShadowStability';19='Get-ShadowCrashReport';20='Repair-ShadowCommon';21='Get-ShadowProcessRules';22='Get-ShadowRecommendations';23='Compare-ShadowProfiles';24='Restore-ShadowAll';25='Show-ShadowBranding'}
Write-Host 'Módulos 01-25 carregados. Use $Shadow25Modules para consultar os nomes das funções.' -ForegroundColor Cyan
